{
  "formatVersion": "1.1",
  "component": {
    "group": "com.redhat.devtools.intellij",
    "module": "intellij-common",
    "version": "1.9.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "intellijPlatformComposedJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "composed-jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.fabric8",
          "module": "kubernetes-client",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "io.fabric8",
          "module": "openshift-client",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-httpclient-okhttp",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.19.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-exec",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "intellij-common-1.9.9.jar",
          "url": "intellij-common-1.9.9.jar",
          "size": 174190,
          "sha512": "b2f49140b382d57e0aee31ce79e6e079eaea68e39e1df52ac69e47a4877fdee935a5e8b84e0bb678f9553ddac3872bde67d8a844278df21bbc4199b49541b5b5",
          "sha256": "762144a3c2c9f41a268d19100cb8bbfe5ad1a5f293d9e283cefca6583c252236",
          "sha1": "c9a21da3eaa7e279ea3c538731f5085bf7354a72",
          "md5": "f6a85536e3c09e74ca4c0dd10642cbe9"
        }
      ]
    }
  ]
}
