{
  "formatVersion": "1.1",
  "component": {
    "group": "com.redhat.devtools.intellij",
    "module": "intellij-common",
    "version": "1.9.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "intellijPlatformComposedJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "composed-jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.fabric8",
          "module": "kubernetes-client",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "io.fabric8",
          "module": "openshift-client",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-httpclient-okhttp",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.17.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-exec",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.twelvemonkeys.common",
          "module": "common-lang",
          "version": {
            "requires": "3.9.4"
          }
        }
      ],
      "files": [
        {
          "name": "intellij-common-1.9.9-SNAPSHOT.jar",
          "url": "intellij-common-1.9.9-SNAPSHOT.jar",
          "size": 174068,
          "sha512": "3070d96d2fd4a38d841a84110162eac89e626d40938041cb4cdb0a0116436c063f5d85890b342dd6902bc2112d33a361077b1f8583f54eabf2df6ffaba214eef",
          "sha256": "9031df4e76b51bde28567d022c2665ae4b7648e9c82cf8531ced7586166d8566",
          "sha1": "2a064b87aaacce5ad66426031b8cb586c6eee501",
          "md5": "7ee7a6e42824b9c33818fff51a095aa6"
        }
      ]
    }
  ]
}
