{
  "formatVersion": "1.1",
  "component": {
    "group": "com.redhat.devtools.intellij",
    "module": "intellij-common",
    "version": "1.9.9-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "intellijPlatformComposedJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "composed-jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.fabric8",
          "module": "kubernetes-client",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "io.fabric8",
          "module": "openshift-client",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-httpclient-okhttp",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-exec",
          "version": {
            "requires": "1.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.twelvemonkeys.common",
          "module": "common-lang",
          "version": {
            "requires": "3.9.4"
          }
        }
      ],
      "files": [
        {
          "name": "intellij-common-1.9.9-SNAPSHOT.jar",
          "url": "intellij-common-1.9.9-SNAPSHOT.jar",
          "size": 174068,
          "sha512": "ed8fd19529aa0d259546f222a2259d0dae1eee07535cf04b8ca017b29962b9aada63db2372d46ae98986b3198b65f9484c647ce42f27fd86aa42aef660279b75",
          "sha256": "40be61844dee525e5cc3e93cc2e499e048eda2cc5ded9db719f33fe83fadbd30",
          "sha1": "f96acd2a7a745c3b2b9fc7fe75399c24b69c744b",
          "md5": "d31ed1fe7d0e47fa994261c0033e8c6c"
        }
      ]
    }
  ]
}
