{
  "formatVersion": "1.1",
  "component": {
    "group": "com.redhat.devtools.intellij",
    "module": "intellij-common",
    "version": "1.9.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "intellijPlatformComposedJar",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "composed-jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "io.fabric8",
          "module": "kubernetes-client",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "io.fabric8",
          "module": "openshift-client",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "io.fabric8",
          "module": "kubernetes-httpclient-okhttp",
          "version": {
            "requires": "7.1.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.18.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-exec",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "intellij-common-1.9.11-SNAPSHOT.jar",
          "url": "intellij-common-1.9.11-SNAPSHOT.jar",
          "size": 174198,
          "sha512": "0aa1b884d716f4459d3c5dbdc8babcad936d34bf0dd83a18442dee13fb72706d3372c13b261246b03ea487f5d49ee4a247b5894a1635f816f35fb8c8ee2421b4",
          "sha256": "79ed76358e3f7569911b2caee801c62198aaafd52b2028479960cde21a390eb9",
          "sha1": "b9b2398fa8ae73f47e979853421bfa2bf3f526bf",
          "md5": "798e4fc9240d7c62f87087d6415c2c24"
        }
      ]
    }
  ]
}
